from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()
migrate = Migrate()


class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True, comment='系统单号')
    url = db.Column(db.String(255), comment='来源网站')
    purl = db.Column(db.String(255), comment='收款站')
    orderid = db.Column(db.String(255), default='', comment='原始单号')
    payway = db.Column(db.Enum('1', '2', '3', '4', '5', '6', '7'), comment='支付方式')
    total = db.Column(db.Integer, nullable=False, comment='总计')
    createtime = db.Column(db.Integer, nullable=False, comment='添加时间')
    status = db.Column(db.Integer, nullable=False, default=1, comment='订单状态')
    username = db.Column(db.String(255), nullable=False, comment='收货人')
    email = db.Column(db.String(255), nullable=False, comment='邮箱')
    telephone = db.Column(db.String(255), nullable=False, comment='电话')
    address = db.Column(db.String(255), nullable=False, comment='收获地址')
    ip = db.Column(db.String(255), nullable=False, comment='IP地址')
    useragent = db.Column(db.String(255), nullable=False, comment='浏览器UA')
    goodsname = db.Column(db.Text, nullable=False, comment='商品名称')
    comment = db.Column(db.String(255), nullable=False, comment='备注')
    paytime = db.Column(db.Integer, nullable=False, comment='支付时间')
    transno = db.Column(db.String(255), nullable=False, comment='支付交易号')
    shippingname = db.Column(db.String(255), default='', comment='物流名称')
    invoiceno = db.Column(db.String(255), default='', comment='运单号')
    account = db.Column(db.String(255), nullable=False)
    wtype = db.Column(db.String(255), default='')
    ipcountry = db.Column(db.String(255), default='')
    msg = db.Column(db.Text)
    is_send = db.Column(db.Integer, default=0)
    admin_id = db.Column(db.Integer, default=1)
    paypalcid = db.Column(db.Text, comment='paypal clientID')
    paypalsid = db.Column(db.Text, comment='paypal sid')
    paymode = db.Column(db.Integer, default=0, comment='测试支付')
    papalmode = db.Column(db.String(1), default='', comment='papal支付模式inoice)paypame')
    fapiaoid = db.Column(db.String(255), default='', comment='paypal账单号')
    cardNumberKeyValue = db.Column(db.String(255), default='')
    expireMonth = db.Column(db.String(255), default='')
    expireYear = db.Column(db.String(255), default='')
    cvv = db.Column(db.String(255), default='')
    currencyCode = db.Column(db.String(255), default='')
    zipcode = db.Column(db.String(255), default='')
    firstname = db.Column(db.String(255), default='')
    order_name = db.Column(db.Text)
    paypal_pass = db.Column(db.String(255), default='')
    country = db.Column(db.String(255), default='')
    city = db.Column(db.String(255), default='')
    state = db.Column(db.String(255), default='')