"""change some to float

Revision ID: 3f12111588db
Revises: 9594e7cdd91e
Create Date: 2023-03-26 17:30:25.733354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f12111588db'
down_revision = '9594e7cdd91e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_comment='总计',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=mysql.INTEGER(),
               existing_comment='总计',
               existing_nullable=False)

    # ### end Alembic commands ###
