"""init migrate

Revision ID: 63debef10df6
Revises: 
Create Date: 2023-03-09 11:00:54.834333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63debef10df6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False, comment='系统单号'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='来源网站'),
    sa.Column('purl', sa.String(length=255), nullable=True, comment='收款站'),
    sa.Column('orderid', sa.String(length=255), nullable=True, comment='原始单号'),
    sa.Column('payway', sa.Enum('1', '2', '3', '4', '5', '6', '7'), nullable=True, comment='支付方式'),
    sa.Column('total', sa.Integer(), nullable=False, comment='总计'),
    sa.Column('createtime', sa.DateTime(), nullable=False, comment='添加时间'),
    sa.Column('status', sa.Integer(), nullable=False, comment='订单状态'),
    sa.Column('username', sa.String(length=255), nullable=False, comment='收货人'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('telephone', sa.String(length=255), nullable=False, comment='电话'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='收获地址'),
    sa.Column('ip', sa.String(length=255), nullable=False, comment='IP地址'),
    sa.Column('useragent', sa.String(length=255), nullable=False, comment='浏览器UA'),
    sa.Column('goodsname', sa.Text(), nullable=False, comment='商品名称'),
    sa.Column('comment', sa.String(length=255), nullable=False, comment='备注'),
    sa.Column('paytime', sa.Integer(), nullable=False, comment='支付时间'),
    sa.Column('transno', sa.String(length=255), nullable=False, comment='支付交易号'),
    sa.Column('shippingname', sa.String(length=255), nullable=True, comment='物流名称'),
    sa.Column('invoiceno', sa.String(length=255), nullable=True, comment='运单号'),
    sa.Column('account', sa.String(length=255), nullable=False),
    sa.Column('wtype', sa.String(length=255), nullable=True),
    sa.Column('ipcountry', sa.String(length=255), nullable=True),
    sa.Column('msg', sa.Text(), nullable=True),
    sa.Column('is_send', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('paypalcid', sa.Text(), nullable=True, comment='paypal clientID'),
    sa.Column('paypalsid', sa.Text(), nullable=True, comment='paypal sid'),
    sa.Column('paymode', sa.Integer(), nullable=True, comment='测试支付'),
    sa.Column('papalmode', sa.String(length=1), nullable=True, comment='papal支付模式inoice)paypame'),
    sa.Column('fapiaoid', sa.String(length=255), nullable=True, comment='paypal账单号'),
    sa.Column('cardNumberKeyValue', sa.String(length=255), nullable=True),
    sa.Column('expireMonth', sa.String(length=255), nullable=True),
    sa.Column('expireYear', sa.String(length=255), nullable=True),
    sa.Column('cvv', sa.String(length=255), nullable=True),
    sa.Column('currencyCode', sa.String(length=255), nullable=True),
    sa.Column('zipcode', sa.String(length=255), nullable=True),
    sa.Column('firstname', sa.String(length=255), nullable=True),
    sa.Column('order_name', sa.Text(), nullable=True),
    sa.Column('paypal_pass', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
