"""add Log

Revision ID: 87ae5ae1ac90
Revises: 49894a386be1
Create Date: 2023-04-19 22:28:06.705703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ae5ae1ac90'
down_revision = '49894a386be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('errorno', sa.String(length=100), nullable=False, comment='错误码'),
    sa.Column('desc', sa.String(length=255), nullable=False, comment='详细描述'),
    sa.Column('createtime', sa.Integer(), nullable=False, comment='创建时间'),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
