"""添加API key到Shop

Revision ID: 9594e7cdd91e
Revises: f906f580eea8
Create Date: 2023-03-22 21:06:40.887605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9594e7cdd91e'
down_revision = 'f906f580eea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apikey', sa.String(length=64), nullable=False, comment='API Key'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.drop_column('apikey')

    # ### end Alembic commands ###
