"""add stripe

Revision ID: e1a7de751aa5
Revises: ebc57335416f
Create Date: 2023-03-12 08:52:16.447728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a7de751aa5'
down_revision = 'ebc57335416f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe',
    sa.Column('id', sa.Integer(), nullable=False, comment='编号'),
    sa.Column('url', sa.String(length=255), nullable=False, comment='收款站地址'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='stripe账户'),
    sa.Column('mode', sa.Enum('0', '1'), nullable=False, comment='账户类型'),
    sa.Column('pays', sa.Enum('2', '1', '3'), nullable=False),
    sa.Column('limitway', sa.Enum('3', '4', '2', '1'), nullable=False, comment='收款限定'),
    sa.Column('onemin', sa.Integer(), nullable=False, comment='单笔最小金额'),
    sa.Column('onemax', sa.Integer(), nullable=False, comment='单笔最大金额'),
    sa.Column('totalmoney', sa.Integer(), nullable=False, comment='限定收款金额'),
    sa.Column('curmoney', sa.Float(), nullable=False, comment='当前收款金额'),
    sa.Column('totalnum', sa.Integer(), nullable=False, comment='限定收款笔数'),
    sa.Column('curnum', sa.Integer(), nullable=False, comment='当前收款笔数'),
    sa.Column('status', sa.Integer(), nullable=False, comment='是否启用'),
    sa.Column('beizhu', sa.Text(), nullable=True, comment='备注'),
    sa.Column('updatetime', sa.Integer(), nullable=True),
    sa.Column('scid', sa.String(length=255), nullable=False),
    sa.Column('lcid', sa.String(length=255), nullable=False),
    sa.Column('ssid', sa.String(length=255), nullable=False),
    sa.Column('lsid', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('0', '1'), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.Column('lasttime', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('purl', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe')
    # ### end Alembic commands ###
