"""add shop model

Revision ID: ebc57335416f
Revises: cf20121a5001
Create Date: 2023-03-10 16:11:21.299611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc57335416f'
down_revision = 'cf20121a5001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False, comment='编号'),
    sa.Column('url', sa.String(length=255), nullable=False, comment='网址'),
    sa.Column('sitegroup', sa.Integer(), nullable=False, comment='收款组'),
    sa.Column('paypaltype', sa.Enum('2', '3', '1'), nullable=False, comment='Paypal账单名称'),
    sa.Column('status', sa.Integer(), nullable=False, comment='是否启用'),
    sa.Column('paypalname', sa.String(length=255), nullable=True, comment='Paypal产品名称'),
    sa.Column('beizhu', sa.Text(), nullable=True, comment='备注'),
    sa.Column('updatetime', sa.Integer(), nullable=False, comment='更新时间'),
    sa.Column('type', sa.Integer(), nullable=True, comment='网站类型'),
    sa.Column('risk', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('paypalname_me', sa.String(length=255), nullable=True),
    sa.Column('donatename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop')
    # ### end Alembic commands ###
