"""add currency

Revision ID: f906f580eea8
Revises: e1a7de751aa5
Create Date: 2023-03-22 11:06:11.187185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f906f580eea8'
down_revision = 'e1a7de751aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False, comment='货币ID'),
    sa.Column('code', sa.String(length=10), nullable=False, comment='币种代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='名称'),
    sa.Column('value', sa.Float(precision=10, asdecimal=2), nullable=False, comment='汇率'),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency')
    # ### end Alembic commands ###
